### ISSUE TITLE
Small audio buffer size issue (<1024)

### ISSUE THREAD

**Issue by AlexMendy** [AndrewJJ/ob_HIIR#1]
Configure audio buffer size < 1024 at 48KHz or 96KHz generate full-scale amplitude self- oscillation.
Thanks for this wrapper. 
Regards. 
Alex

**Comment by AndrewJJ** [comment]
Hi Alex - I'm not seeing this behaviour. Can you give me a detailed repro?

**Comment by AlexMendy** [comment]
Hello Andrew thanks for your quick reply.
For sure the code is targeted for Intel/Amd x64 VST and AU plugins. I have the issue on Windows 10 and MacOS 10.15 with RME Fireface audio Asio Driver. If buffer size is >= to 1024, everything run smooth. For debug purpose, I just upsample and downsample by a factor 2 then apply gain. If gain is not apply then I don't have oscillation.

Here is the way I prepare h_iir oversampler.
`void Proc::prepare(dsp::ProcessSpec spec) {
    const int ov_factor = 2;
    m_hiir_ov.prepare(ov_factor, spec.numChannels, spec.maximumBlockSize);
}`

Oscillate:
`		m_hiir_ov.upSample(buffer);	 	
		m_hiir_ov.downSample(buffer);
		buffer.applyGain(Decibels::decibelsToGain(Gain));
`
Run smooth:
`		m_hiir_ov.upSample(buffer);	 	
		m_hiir_ov.downSample(buffer);
`
Regards

**Comment by AndrewJJ** [comment]
Hi Alex,

Your example doesn't look quite right as it is applying the gain after downsampling. Did you mean instead to apply the gain between the up and down sample?

If you're doing that then you need to make sure you process the full length of the oversampled buffer. So for an oversampling factor of 2, you need to process numSamples * 2. If you don't then you are effectively modulating the signal with a square wave.

Try something like this:

```
process (const dsp::ProcessContextReplacing<float>& context)
{
  const auto numChannels = context.getInputBlock().getNumChannels();
  const auto numSamples = context.getInputBlock().getNumSamples();
  const auto numSamplesOversampled = numSamples * 2;
  const auto gain = Decibels::decibelsToGain (Gain);
  hiir.setSize(numSamples);
  for (auto ch = 0; ch < numChannels; ++ch)
  {
      hiir.upSample(ch, context.getInputBlock().getChannelPointer(ch));
      for (auto i = 0; i < numSamplesOversampled; ++i)
          hiir.getOverSampledData(ch)[i] *= gain;
      hiir.downSample(ch, context.getOutputBlock().getChannelPointer(ch));
  }
}
```

If you just set numSamplesOversampled = numSamples I think you'll see the problem you are describing.

**Comment by AlexMendy** [comment]
Hi Andrew,

I try your code and it run without problem at any buffer size I try 48/64/128.
About the gain, I would apply it to downsampled buffer. And I apply it after downsample with your code and it run well too.
I don't really know why but I suppose to use `const dsp::ProcessContextReplacing<float>& context` avoid buffer corruption.
Thanks very much for helping to solve my problem.
Regards
