### ISSUE TITLE
Copyright statement is incorrect.

### ISSUE THREAD

**Issue by rerdavies** [AndrewJJ/ob_HIIR#3]
Specifically, the license description on the right-hand column of the main page of your project says MIT Licensed. This is wrong, It should say that the project has a GPL 3.0 license.

Because you have included code that is licensed under the GPL 3 license, the entire project is now governed by the more restrictive GPL 3 license.

By mis-stating the license, you put others at risk of  having their code virally infected with the GPL 3.0 license.  For those of us who have worked to preserve MIT licenses in our own works, this is a VERY big deal.

**Comment by AndrewJJ** [comment]
Hi Robin - thanks for your interest. The included code from Laurent de Soras is LGPL 2.1 which in my understanding doesn't "virally infect" MIT. However I am not a lawyer and am happy to be educated!

If you're referring to JUCE, then that is indeed available under GPL v3. However I am not publishing any of the JUCE source code in this repo. For reference, [the original author has commented on this](https://forum.juce.com/t/open-source-without-gpl/29721/2?u=andrewj) and claims that publishing a library with an external dependency on JUCE is OK.

**Comment by rerdavies** [comment]
Then perhaps you could revise the license to LGPL 2.1.  Although I'm not
sure that's actually better, since you lose the link exception as soon as
you modify the source to use it in a non-Juice environment. (As did you,
when you modified it).

Not actually an issue for me at this point, because I've since written my
own; but it would be kindness to those who follow me to update the license
description.

**Comment by AndrewJJ** [comment]
I'm happy to update the license if that helps, I'm just not clear what the best approach is here.  However, I note that there are newer versions of HIIR now and those are under the WTFPL. So maybe I should just update this repo.

**Comment by rerdavies** [comment]
First time I've heard of it, but it's certainly even more permissive than
the MIT license.

That would have worked for me.

Thanks.

**Comment by AndrewJJ** [comment]
License updated
